#!/bin/bash
# Resolves the op:// secret references in .env via the 1Password CLI and
# writes the real values to ~/.env.local.sh so every shell in the container
# already has them exported - no more `op run --env-file=./.env -- ...`
# before each command.
#
# Runs automatically on every container start (see postStartCommand in
# devcontainer.json), so it stays fresh across restarts and rebuilds.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"
OUT_FILE="$HOME/.env.local.sh"

if [ ! -f "$ENV_FILE" ]; then
    echo "resolve-env: no .env file at $ENV_FILE, skipping."
    exit 0
fi

{
    echo "# Auto-generated by .devcontainer/scripts/resolve-env.sh - do not edit by hand."
    echo "# Regenerated on every container start from $ENV_FILE via 1Password."
    op run --no-masking --env-file="$ENV_FILE" -- env | while IFS='=' read -r key value; do
        if grep -q "^${key}=" "$ENV_FILE"; then
            printf 'export %s=%q\n' "$key" "$value"
        fi
    done
} > "$OUT_FILE"

chmod 600 "$OUT_FILE"
echo "resolve-env: wrote resolved secrets to $OUT_FILE"
