service: intervention-tracker

image: troptropcontent/intervention-tracker

servers:
  web:
    - 51.254.129.231
  jobs:
    hosts:
      - 51.254.129.231
    cmd: ./background_jobs start

proxy:
  ssl: true
  host: antivol.maintenanceautomatisme.fr

registry:
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  clear:
    DB_HOST: 192.168.0.2
  secret:
    - RAILS_MASTER_KEY

ssh:
  user: ubuntu

accessories:
  database:
    image: postgres:17.5
    env:
      secret:
        - POSTGRES_PASSWORD
    roles:
      - web
    directories:
      - data:/var/lib/postgresql/data
  gotemberg:
    image: gotenberg/gotenberg:8
    roles:
      - web
