service: intervention-tracker

image: troptropcontent/intervention-tracker

servers:
  web:
    - 51.254.129.231
  jobs:
    hosts:
      - 51.254.129.231
    cmd: ./background_jobs start

proxy:
  ssl: true
  host: antivol.maintenanceautomatisme.fr

registry:
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  clear:
    GO_ENV: production
  secret:
    - SMTP_USERNAME
    - SMTP_PASSWORD
    - SMTP_HOST
    - SMTP_PORT
    - S3_ENDPOINT
    - S3_ACCESS_KEY
    - S3_SECRET_KEY
    - S3_REGION

ssh:
  user: ubuntu

accessories:
  database:
    image: postgres:17.5
    roles:
      - web
    directories:
      - data:/var/lib/postgresql/data
  gotemberg:
    image: gotenberg/gotenberg:8
    roles:
      - web
